### ISSUE TITLE
.net agent windows service instrumentation

### ISSUE THREAD

**Issue by akemner** [Appdynamics/appdynamics-cookbooks#16]
some of our .net applications are windows services and most of the time there are more than one application on a server instance. 

support for enabling instrumentation for a windows service should be included with the dotnet_agent recipe

**Comment by dkoepke** [comment]
Does https://github.com/Appdynamics/appdynamics-cookbooks/pull/18 address this?

**Comment by thiru-chidambaram** [comment]
Yes.

**Comment by akemner** [comment]
resolved in https://github.com/Appdynamics/appdynamics-cookbooks/pull/26
