### ISSUE TITLE
java_agent - agent cannot create logs unless ran as root

### ISSUE THREAD

**Issue by akemner** [Appdynamics/appdynamics-cookbooks#33]
java_agent - agent cannot create logs unless ran as root

there is no directory resource for the install_dir(only install_dir/conf). since the agent.zip gets unzipped in the install_dir and the logs get created under that, this ['java_agent']['owner'] only applied to the config dir. 

https://github.com/Appdynamics/appdynamics-cookbooks/pull/36 addresses this and adds some rspec and serverspec testing

**Comment by dkoepke** [comment]
Fixed in #36.
