### ISSUE TITLE
kitchen fails for nodejs & python on ubuntu - libexpat1-dev_2.0.1-7.2ubuntu1.1_amd64.deb  404  Not Found

### ISSUE THREAD

**Issue by akemner** [Appdynamics/appdynamics-cookbooks#37]
kitchen is failing for both ubuntu nodejs and python with libexpat1-dev_2.0.1-7.2ubuntu1.1_amd64.deb  404  Not Found

kitchen test nodejs-agent-ubuntu

STDERR: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.2.0-89.127_amd64.deb  404  Not Found [IP: 91.189.92.200 80] E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
---- End output of apt-get -q -y install build-essential=11.5ubuntu2.1 ----
Ran apt-get -q -y install build-essential=11.5ubuntu2.1 returned 100
[2015-09-17T20:50:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

kitchen test python-agent-ubuntu

STDERR: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.2.0-89.127_amd64.deb  404  Not Found [IP: 91.189.91.14 80]
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/e/expat/libexpat1-dev_2.0.1-7.2ubuntu1.1_amd64.deb  404  Not Found [IP: 91.189.91.14 80] E: Unable to fetch some archives, maybe run apt-get update or try with --
fix-missing?
---- End output of apt-get -q -y install python-dev=2.7.3-0ubuntu2.2 ----
Ran apt-get -q -y install python-dev=2.7.3-0ubuntu2.2 returned 100
[2015-09-17T23:02:05+00:00] FATAL: Chef::Exceptions::ChildConvergeError:Chef run process exited unsuccessfully (exit code 1)

**Comment by dkoepke** [comment]
It looks like `apt-get update` wasn't run. Have we lost the `recipe[apt::default]`?

**Comment by akemner** [comment]
it looks like that recipe was never on the node or python suite, only machine and java. i'll re-test with that added

**Comment by akemner** [comment]
ok failed tests pass with recipe[apt::default] in the runlist

**Comment by dkoepke** [comment]
Fixed in #38.
