### ISSUE TITLE
Java Agent Install

### ISSUE THREAD

**Issue by dkoepke** [Appdynamics/appdynamics-cookbooks#4]

**Comment by dkoepke** [comment]
Needs RSpec tests, but kitchen convergence tests are passing and manually verified to install Java agent. Since the location of the Java application's startup script can vary so much, we cannot do much about helping people add the `-javaagent` flag. Will add a node attribute to assist.

**Comment by dkoepke** [comment]
Also needs docs in README.md.

**Comment by akemner** [comment]
same questions as the machine agent, i see apt being used for the kitchen test for the java agent but not using yum for centos

**Comment by akemner** [comment]
i added rspec and serverspec testing in https://github.com/Appdynamics/appdynamics-cookbooks/pull/32

**Comment by dkoepke** [comment]
Fixed in #36.
