### ISSUE TITLE
Release 0.3.0?

### ISSUE THREAD

**Issue by spuder** [Appdynamics/appdynamics-cookbooks#55]
Could you release version 0.3.0 or 0.2.6 that contains the fixes in #53 and #54 ?

Can't use these changes yet without blind-reving the 0.2.5 cookbook or other berkshelf hackery.

**Comment by spuder** [comment]
Any update on this? We have stopped using app dynamics because we can't deploy it without breaking our release process.

**Comment by dkoepke** [comment]
Resolved in #57. Created tag `v0.3.0` as well.
