### ISSUE TITLE
Latest change (dependency version pinning) breaks Chef11

### ISSUE THREAD

**Issue by nothsa** [Appdynamics/appdynamics-cookbooks#56]
The new version pins in metadata.rb breaks support for Chef 10 and Chef 11. Please either revert the changes or update your README.rb to reflect Chef 12 as a requirement.

**Comment by dkoepke** [comment]
I'll fix this ASAP.

**Comment by nothsa** [comment]
Much appreciated.

I've just finished spending two days of diagnosis, tracking down all of the dependencies that the new AppDynamics version pins break. Even had to swap out a few other community cookbooks and disable AppDynamics completely on our OpsWorks projects as OpsWorks has limited Chef version support  x_x

**Comment by spuder** [comment]
The version pinning was pinned against all the latest versions except for ark, which was held back at version 1.1.0 (1.2.0 broke chef 12). 

Are there version pins that work with both chef 12 and chef 11 ? That would be a better solution.

**Comment by nothsa** [comment]
@spuder Ideally, if you're going to pin a package, then pinning to the lowest version that your package actually requires (instead of just the latest) allows it to be included more easily in a variety of setups. I don't know which versions of the packages work with Chef 10/11 as I would have to spend time doing the research and testing them all. I've already wasted 2 days on this, which has pushed us behind schedule, and I can't afford any more :(

**Comment by spuder** [comment]
@nothsa Can you run `knife cookbook show foo` on chef 10 and chef 11 servers?

If so, the following will show all the installed versions

bash
```
cookbooks=(windows python nodejs java apt powershell ark)
for i in "${cookbooks[@]}"; do knife cookbook show $i; done
```

powershell
```
$cookbooks=("windows","python","nodejs","java","apt","powershell","ark")
foreach ($cookbook in $cookbooks) {
    knife cookbook show $cookbook
}
```

Which shows on my chef server: 
```
windows   2.0.2  1.44.3  1.44.1  1.43.0  1.40.0  1.39.2  1.39.1  1.39.0  1.38.4  1.38.3  1.38.2  1.38.1  1.38.0
python   1.4.6
nodejs   2.4.4  2.4.0
java   1.42.0  1.40.0  1.39.0  1.36.0  1.35.0  1.31.0  1.29.0  1.28.0
apt   4.0.2  4.0.1  3.0.0  2.9.2  2.8.2  2.8.1  2.7.0  2.6.1  2.6.0  2.3.10
powershell   3.2.3  3.2.2
ark   1.2.0  1.0.1  0.9.0
```

**Comment by nothsa** [comment]
The problem is not the chef _server_ version, it's the chef _client_ version.

We don't use a chef servers for the community cookbooks, we use Berkshelf to resolve dependencies which downloads community cookbooks from the chef supermarket (https://supermarket.chef.io/), so we would have access to all the versions that are in the supermarket:

**windows**: 72 versions - https://supermarket.chef.io/cookbooks/windows
**python**: 19 versions - https://supermarket.chef.io/cookbooks/python
**nodejs**: 25 versions - https://supermarket.chef.io/cookbooks/nodejs
**java**: 67 versions - https://supermarket.chef.io/cookbooks/java
**apt**: 55 versions - https://supermarket.chef.io/cookbooks/apt
**powershell**: 26 versions - https://supermarket.chef.io/cookbooks/powershell
**ark**: 28 versions - https://supermarket.chef.io/cookbooks/ark

If you want to check if they have a specific version available (they should have _every_ version), you check in the version drop-down.

**Comment by dkoepke** [comment]
@nothsa @spuder Based on the published compatibility information, I've pinned `apt` and `powershell` at versions that advertise Chef 11+ support in d844a17. If either you have time to spare to check against your Chef installs, that'd be a huge help.

**Comment by spuder** [comment]
I tested d844a17169f5470b19fc3211f1aa87323282b36a with chef 12.14.60 on windows 2012r2. Everything looks good to me.

**Comment by dkoepke** [comment]
@nothsa I believe that v0.3.0 fixes this issue.
