### ISSUE TITLE
Tag version 3.0.1

### ISSUE THREAD

**Issue by spuder** [Appdynamics/appdynamics-cookbooks#60]
The metatdata.rb shows that 3.0.1 is the latest version, yet there isn't a github tag that points to that version. 

That means that users need to do something ugly like this in the berksfile. 

```
source "https://supermarket.chef.io"

metadata

cookbook 'appdynamics', '~> 0.3.1', github: "Appdynamics/appdynamics-cookbooks", ref: "ddfdc4b59005c8ce36c9f7b1f95a8df2dab98e09"
```

**Comment by dkoepke** [comment]
Tagged v0.3.1
