### ISSUE TITLE
Service stop does not work for machine agent and probably others

### ISSUE THREAD

**Issue by driskell** [Appdynamics/appdynamics-cookbooks#67]
The `killproc` in the init.d script is attempting to find `run.sh`. However, this exits on start and leaves behind the `java` process. Ideally, the PID of the started Java process should be stored and killproc given `java` as process name and the stored PID.

Might try and build this and pull request soon.

**Comment by amit5000** [comment]
Also it starts multiple machine agents and doesnt check if one is already running.

**Comment by dkoepke** [comment]
Fixed in #70
