### ISSUE TITLE
java agent enable SSL

### ISSUE THREAD

**Issue by akemner** [Appdynamics/appdynamics-cookbooks#9]
by default ssl is disabled for agent communication to controller. desire is to have an attribute to enable ssl

**Comment by dkoepke** [comment]
Can you provide an example of a generated `controller-info.xml` where the SSL is disabled by default? SSL should be enabled by default in the cookbook. The `node['appdynamics']['controller']['ssl']` attribute defaults to `true` in `attributes/default.rb` and is injected into the generated `controller-info.xml` via `@controller_ssl`.

**Comment by enigmatic00** [comment]
You're right. The controller-info.xml does get populated with the correct SSL settings, however, despite that, we still had to augment the java startup script with a couple of properties to get the ssl communication to work. A snippet of how we made it work: 

```
 -Dappdynamics.controller.port=443 -Dappdynamics.controller.ssl.enabled=true -javaagent:/opt/appdynamics/javaagent.jar -Xms256m -Xmx1g -XX:MaxPermSize=256m -Djava.awt.headless=true

```

**Comment by dkoepke** [comment]
Closing this issue. The generated `controller-info.xml` from the cookbook was correct. Not clear whether this was an issue with the Java agent (I don't see any reports of it internally), or a problem with the specific deployment. (Perhaps there was another config file overriding the generated one?)
